version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bandito-metube_metube_1
      APP_PORT: 8081

  metube:
    image: ghcr.io/alexta69/metube
    restart: on-failure
    volumes:
      - ${UMBREL_ROOT}/data/storage/downloads/metube:/downloads
